Xapi_vdi.check_operation_error: checks for cbt_enabled
Add checks to disallow operations that cannot be called if CBT is
enabled. The `mirror operation refers to storage motion, so it is not
allowed when CBT is turned on.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>