Build that broke without the fixed autogeneration code
Build failed with

File "ocaml/xapi-types/aPI.ml", line 599, characters 116-137:
Error: Unbound type constructor nBD_server_info_t_set